# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish package to Node.js

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v3
  
      - name: 设置node
        uses: actions/setup-node@v3
        with: 
          # node版本
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
        # 发布npm包
      - name: Publish to npm
        run: npm publish --access public
        env:
         # npm 账号下 Access Tokens -> Generate New Token -> Granular Access Token 复制到github仓库下Settings -> Secrets and variables -> Action -> New repository secret
         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_KEY}}
         
         # 生成位置 github账号下 Settings/Developer Settings -> Personal access tokens(Fine-graubed tokens beta)
         GITHUB_TOKEN: ${{secrets.secure_key_smith}}
