# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish package to Node.js

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
  runs-on: ubuntu-latest
  steps:
    - name: 检查分支
      uses: actions/checkout@main

    - name: 设置node
      uses: actions/setup-node@main
      with: 
        # node版本
        node-version: 16

      # 发布npm包
    - name: Publish to npm
       run: |
         npm config set //registry.npmjs.org/:_authToken=$npm_tokenKey
         npm publish
       env:
       NODE_AUTH_TOKEN: ${{secrets.npm_tokenKey}}
